sudo: false
notifications:
  email: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libopencv-dev
before_script:
  - mkdir ../build
  - cd ../build
script:
  # Run CMake in order to generate makefile
  - cmake ../itseez-ws-2016-practice
  # Build
  - make
  # Run regression tests
  - ./bin/test_skeleton
  # Run performance tests
  - ./bin/perf_skeleton --gtest_output=xml:perf_report.xml
  # Print performance metrics
  - ../itseez-ws-2016-practice/3rdparty/opencv_ptest/misc/summary.py ./perf_report.xml
  # Run sample application
  - ./bin/skeleton --image ./bin/testdata/page.png
